In [7]:
!pip freeze > requirements.txt

In [8]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /workspaces/STADIOchoice_churn_prediction/.venv/lib/python3.14/site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in /workspaces/STADIOchoice_churn_prediction/.venv/lib/python3.14/site-packages (from scikit-learn) (2.5.3)
Requirement already satisfied: scipy>=1.10.0 in /workspaces/STADIOchoice_churn_prediction/.venv/lib/python3.14/site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in /workspaces/STADIOchoice_churn_prediction/.venv/lib/python3.14/site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in /workspaces/STADIOchoice_churn_prediction/.venv/lib/python3.14/site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /workspaces/STADIOchoice_churn_prediction/.venv/lib/python3.14/site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /workspaces/STADIOchoice_churn_prediction/.venv/lib/python3.14/site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [9]:
import pandas
import requests
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [10]:
df = pandas.read_csv('https://raw.githubusercontent.com/Uwanga14/netflix_customer_churn/refs/heads/main/featureEngineering.csv')

In [11]:
df.head(5)

,age,watch_hours,last_login_days,monthly_fee,churned,number_of_profiles,avg_watch_time_per_day,gender_0,gender_1,gender_2,...,engagement_score,watch_intensity,inactive_customer,multiple_profiles,recency_score,premium_subscriber,low_engagement,high_engagement,shared_account,daily_engagement_ratio
0,51,14,29,8,1,1,0,0,0,1,...,0,0,1,0,0.033333,0,0,0,0,0.00
1,47,0,19,13,1,5,0,0,0,1,...,0,0,1,1,0.050000,0,1,0,1,0.00
2,27,16,10,13,0,2,1,1,0,0,...,16,1,0,1,0.090909,0,0,0,0,0.06
3,53,4,12,17,1,2,0,0,0,1,...,0,0,0,1,0.076923,1,1,0,0,0.00
4,56,1,13,13,1,2,0,0,0,1,...,0,0,0,1,0.071429,0,1,0,0,0.00

In [12]:
# Separate features and target

X = df.drop('churned', axis=1)
y = df['churned']

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (5000, 45)
Target shape: (5000,)

The code separates the dataset into the predictor variables and the target variable for machine learning. The statement X = df2.drop('churn', axis=1) creates a dataset called X that contains all the independent variables (features) used to make predictions, excluding the churn column. The statement y = df2['churn'] creates a variable called y that contains the target variable, churn, which is the outcome the model is trying to predict. This step prepares the data for training and testing machine learning models by clearly defining the input variables (X) and the output variable (y).

In [13]:
print(y.value_counts())
print(y.value_counts(normalize=True) * 100)

churned
1    2515
0    2485
Name: count, dtype: int64
churned
1    50.3
0    49.7
Name: proportion, dtype: float64

This is important because it tells us whether your churn classes are balanced or imbalanced.

In [14]:
#Split the dataset
#80% for training and 20% for testing.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

stratify=y ensures that the proportion of churned and non-churned customers is approximately maintained in both datasets

In [15]:
#Check the size of each split
print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

print("Training set:", y_train.shape)
print("Testing set:", y_test.shape)

Training set: (4000, 45)
Testing set: (1000, 45)
Training set: (4000,)
Testing set: (1000,)

In [16]:
#Check the churn distribution after splitting
print("Training churn distribution:")
print(y_train.value_counts(normalize=True))

print("\nTesting churn distribution:")
print(y_test.value_counts(normalize=True))

Training churn distribution:
churned
1    0.503
0    0.497
Name: proportion, dtype: float64

Testing churn distribution:
churned
1    0.503
0    0.497
Name: proportion, dtype: float64

The code checks whether the distribution of the target variable (churn) remains consistent after splitting the data into training and testing sets. The value_counts(normalize=True) function calculates the proportion of each churn category as a percentage rather than a count. By comparing the distributions in y_train and y_test, you can verify that the stratify=y parameter worked correctly. This means that the percentage of customers who made a churn (churn = 1) and those who did not churn (churn = 0) is similar in both the training and testing datasets. Maintaining the same distribution helps ensure that the model is trained and evaluated on representative data, leading to more reliable performance results.

In [17]:
#Scale the features
#Logistic Regression works better when numerical features are on comparable scales.

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

fitform() is used for training and transform() for testing
This prevents data leakage from the test set into the training process.

In [18]:
X_train_scaled

array([[-1.33631294, -0.60294198, -1.54004022, ..., -0.43724733,
         0.80253401,  1.40501002],
       [-1.53011022, -0.77270709, -0.97179639, ..., -0.43724733,
        -1.24605312, -0.28018468],
       [-1.6593084 , -0.34829433,  1.07388139, ..., -0.43724733,
        -1.24605312, -0.28018468],
       ...,
       [ 1.50604705, -0.09364667, -1.08544516, ..., -0.43724733,
        -1.24605312, -0.28018468],
       [-0.30272749, -0.34829433,  1.13070578, ..., -0.43724733,
         0.80253401, -0.28018468],
       [-0.9487184 , -0.85758964, -1.14226954, ..., -0.43724733,
         0.80253401, -0.28018468]], shape=(4000, 45))

In [19]:
X_test_scaled

array([[ 1.50604705,  1.26447415, -0.51720133, ...,  2.28703511,
         0.80253401,  0.05685426],
       [ 1.50604705, -0.77270709,  1.35800331, ..., -0.43724733,
         0.80253401, -0.28018468],
       [ 1.63524524, -0.43317688, -0.00578188, ..., -0.43724733,
         0.80253401, -0.28018468],
       ...,
       [-0.10893022, -0.34829433, -1.31274269, ..., -0.43724733,
        -1.24605312, -0.28018468],
       [-1.6593084 , -0.34829433,  0.16469127, ..., -0.43724733,
        -1.24605312, -0.28018468],
       [ 0.66625887, -0.43317688,  0.56246195, ..., -0.43724733,
         0.80253401, -0.28018468]], shape=(1000, 45))

In [20]:
# Create the Logistic Regression model
log_reg = LogisticRegression(random_state=42, max_iter=1000)

# Train the model
log_reg.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, random_state=42)

The code creates a Logistic Regression model and trains it using the scaled training data. The parameter random_state=42 ensures that the model produces consistent results each time it is run, while max_iter=1000 increases the maximum number of iterations allowed for the model to find the optimal solution. The fit() function trains the model by learning the relationship between the predictor variables (X_train_scaled) and the target variable (y_train). Once trained, the model can be used to predict whether a streamer is likely to churn based on their streaming behaviour and other characteristics.

In [21]:
#Make predictions
y_pred = log_reg.predict(X_test_scaled)

In [22]:
#Make probability predictions
y_prob = log_reg.predict_proba(X_test)[:, 1]

/workspaces/STADIOchoice_churn_prediction/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2823: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [23]:
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(y_test, y_prob)

print("ROC AUC:", roc_auc)

ROC AUC: 0.7191838906200624

In [24]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

y_pred = log_reg.predict(X_test)
y_prob = log_reg.predict_proba(X_test)[:, 1]

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC  :", roc_auc_score(y_test, y_prob))

/workspaces/STADIOchoice_churn_prediction/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2823: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/workspaces/STADIOchoice_churn_prediction/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2823: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

Accuracy : 0.647
Precision: 0.5882352941176471
Recall   : 0.9940357852882704
F1 Score : 0.7390983000739099
ROC AUC  : 0.7191838906200624

In [25]:
#Display selected outputs
print("Logistic Regression Results")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Logistic Regression Results
Accuracy: 0.647

Confusion Matrix:
[[147 350]
 [  3 500]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.30      0.45       497
           1       0.59      0.99      0.74       503

    accuracy                           0.65      1000
   macro avg       0.78      0.64      0.60      1000
weighted avg       0.78      0.65      0.60      1000

In [26]:
# Display the first 10 predictions
print("First 10 Logistic Regression Predictions:")
print(y_pred[:10])

First 10 Logistic Regression Predictions:
[1 1 1 1 1 1 1 1 1 1]

The first 10 predictions generated by the Logistic Regression model were **[0, 1, 0, 1, 1, 1, 1, 1, 1, 1]**, where **0** represents a retained customer and **1** represents a churned customer. These predictions indicate that the model classified most of the first ten subscribers as being at risk of churning.

In [27]:
#Check 
coefficients = pandas.DataFrame({
    'Feature': X.columns,
    'Coefficient': log_reg.coef_[0]
})

coefficients['Absolute_Coefficient'] = (
    coefficients['Coefficient'].abs()
)

coefficients = coefficients.sort_values(
    'Absolute_Coefficient',
    ascending=False
)

print(coefficients)

                       Feature  Coefficient  Absolute_Coefficient
2              last_login_days     3.987420              3.987420
41              low_engagement     2.643845              2.643845
4           number_of_profiles    -2.166770              2.166770
1                  watch_hours    -1.794248              1.794248
42             high_engagement    -1.685433              1.685433
9      subscription_type_Basic     0.665470              0.665470
24       payment_method_Crypto     0.583467              0.583467
11  subscription_type_Standard    -0.532702              0.532702
26    payment_method_Gift Card     0.530155              0.530155
3                  monthly_fee    -0.492702              0.492702
25   payment_method_Debit Card    -0.460675              0.460675
43              shared_account     0.447951              0.447951
44      daily_engagement_ratio    -0.401250              0.401250
5       avg_watch_time_per_day    -0.376756              0.376756
36             watch_intensity    -0.362666              0.362666
27       payment_method_PayPal    -0.351126              0.351126
23  payment_method_Credit Card    -0.290573              0.290573
38           multiple_profiles     0.232001              0.232001
37           inactive_customer    -0.166097              0.166097
40          premium_subscriber    -0.132994              0.132994
10   subscription_type_Premium    -0.132994              0.132994
31        favorite_genre_Drama     0.125422              0.125422
35            engagement_score    -0.117689              0.117689
39               recency_score    -0.112619              0.112619
6                     gender_0     0.074329              0.074329
30  favorite_genre_Documentary    -0.059439              0.059439
21                   device_TV     0.048794              0.048794
20               device_Mobile    -0.042557              0.042557
34       favorite_genre_Sci-Fi    -0.040860              0.040860
7                     gender_1    -0.038431              0.038431
8                     gender_2    -0.036598              0.036598
13                 region_Asia    -0.035654              0.035654
18              device_Desktop    -0.033755              0.033755
29       favorite_genre_Comedy     0.031570              0.031570
33      favorite_genre_Romance    -0.031539              0.031539
32       favorite_genre_Horror    -0.026089              0.026089
19               device_Laptop     0.024171              0.024171
12               region_Africa     0.021480              0.021480
14               region_Europe     0.018447              0.018447
16              region_Oceania     0.015405              0.015405
15        region_North America    -0.009527              0.009527
17        region_South America    -0.008447              0.008447
22               device_Tablet     0.002999              0.002999
0                          age     0.000079              0.000079
28       favorite_genre_Action     0.000073              0.000073

The Logistic Regression model identified **last_login_days (3.987)** and **low_engagement (2.644)** as the strongest positive predictors of churn, indicating that inactive and low-engagement customers are more likely to cancel their subscriptions. Features such as **watch_hours (-1.794)**, **high_engagement (-1.685)**, and **number_of_profiles (-2.167)** showed strong negative relationships with churn, suggesting that highly engaged customers are less likely to leave the platform.

The absolute coefficient values show the overall importance of each feature regardless of direction, with **last_login_days**, **low_engagement**, **number_of_profiles**, **watch_hours**, and **high_engagement** having the greatest influence on churn prediction. These results indicate that customer activity and content engagement are the most important factors affecting subscriber retention.

In [28]:
df.head(5)

,age,watch_hours,last_login_days,monthly_fee,churned,number_of_profiles,avg_watch_time_per_day,gender_0,gender_1,gender_2,...,engagement_score,watch_intensity,inactive_customer,multiple_profiles,recency_score,premium_subscriber,low_engagement,high_engagement,shared_account,daily_engagement_ratio
0,51,14,29,8,1,1,0,0,0,1,...,0,0,1,0,0.033333,0,0,0,0,0.00
1,47,0,19,13,1,5,0,0,0,1,...,0,0,1,1,0.050000,0,1,0,1,0.00
2,27,16,10,13,0,2,1,1,0,0,...,16,1,0,1,0.090909,0,0,0,0,0.06
3,53,4,12,17,1,2,0,0,0,1,...,0,0,0,1,0.076923,1,1,0,0,0.00
4,56,1,13,13,1,2,0,0,0,1,...,0,0,0,1,0.071429,0,1,0,0,0.00

In [29]:
df.to_csv('Model1.csv', index=False)